# Generated by Django 4.2.1 on 2023-06-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_class_choices_alter_student_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='student',
            name='marklist',
            field=models.FileField(upload_to='static/marklists/'),
        ),
    ]
